// <auto-generated />
using System;
using AiHelpers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiHelpers.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260828110023_AddGeneratedDocuments")]
    partial class AddGeneratedDocuments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AiHelpers.Data.Entities.AccountingEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<int?>("HelperDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("HelperName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("HelperDefinitionId");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("AccountingEntries");
                });

            modelBuilder.Entity("AiHelpers.Data.Entities.ArticleStoreItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Access")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ArticleHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("ArticleStoreItems");
                });

            modelBuilder.Entity("AiHelpers.Data.Entities.CallbackEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CallbackGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HelperDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("HelperName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Initiator")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("int");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StopReason")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CallbackGuid")
                        .IsUnique();

                    b.HasIndex("HelperDefinitionId");

                    b.ToTable("CallbackEntries");
                });

            modelBuilder.Entity("AiHelpers.Data.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DidSaveTime")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Failures")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int?>("HelperDefinitionId")
                        .HasColumnType("int");

                    b.Property<int?>("HoursSaved")
                        .HasColumnType("int");

                    b.Property<string>("Improvements")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<byte?>("MinutesSaved")
                        .HasColumnType("tinyint");

                    b.Property<string>("OtherComments")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<byte>("Overall")
                        .HasColumnType("tinyint");

                    b.Property<string>("Successes")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("HelperDefinitionId");

                    b.ToTable("FeedbackEntries");
                });

            modelBuilder.Entity("AiHelpers.Data.Entities.GeneratedDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("HelperDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByEmail");

                    b.HasIndex("HelperDefinitionId");

                    b.ToTable("GeneratedDocuments");
                });

            modelBuilder.Entity("AiHelpers.Data.Entities.HelperCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("HelperCategories");
                });

            modelBuilder.Entity("AiHelpers.Data.Entities.HelperContextQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HelperDefinitionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UsageInstruction")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("HelperDefinitionId");

                    b.ToTable("HelperContextQuestions");
                });

            modelBuilder.Entity("AiHelpers.Data.Entities.HelperDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Adherence")
                        .HasPrecision(8, 5)
                        .HasColumnType("decimal(8,5)");

                    b.Property<decimal?>("AdherenceAdjustmentAllowance")
                        .HasPrecision(8, 5)
                        .HasColumnType("decimal(8,5)");

                    b.Property<bool>("AllowContext")
                        .HasColumnType("bit");

                    b.Property<string>("ContextPrompt")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ContextQuestionsIntro")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<decimal?>("Creativity")
                        .HasPrecision(8, 5)
                        .HasColumnType("decimal(8,5)");

                    b.Property<decimal?>("CreativityAdjustmentAllowance")
                        .HasPrecision(8, 5)
                        .HasColumnType("decimal(8,5)");

                    b.Property<int?>("DefaultStylesheetId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Effort")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("HasKnowledge")
                        .HasColumnType("bit");

                    b.Property<int?>("HelperCategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("bit");

                    b.Property<string>("KnowledgeData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KnowledgeFileType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("KnowledgePrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LlmDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("Methodology")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("OutputFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputSchemaJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PrimaryPurpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SpecialInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StyleTone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetAudience")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultStylesheetId");

                    b.HasIndex("HelperCategoryId");

                    b.HasIndex("LlmDefinitionId");

                    b.ToTable("HelperDefinitions", t =>
                        {
                            t.HasCheckConstraint("CK_HelperDefinition_ExternalUrl", "([IsExternal] = 0 AND [ExternalUrl] IS NULL) OR ([IsExternal] = 1 AND [ExternalUrl] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("AiHelpers.Data.Entities.HelperFavorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HelperDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("HelperDefinitionId");

                    b.HasIndex("UserEmail", "HelperDefinitionId")
                        .IsUnique();

                    b.ToTable("HelperFavorites");
                });

            modelBuilder.Entity("AiHelpers.Data.Entities.LlmDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DefaultAdherence")
                        .HasPrecision(8, 5)
                        .HasColumnType("decimal(8,5)");

                    b.Property<decimal>("DefaultCreativity")
                        .HasPrecision(8, 5)
                        .HasColumnType("decimal(8,5)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal?>("InputTokenCost")
                        .HasPrecision(8, 5)
                        .HasColumnType("decimal(8,5)");

                    b.Property<int?>("MaxTokens")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal?>("OutputTokenCost")
                        .HasPrecision(8, 5)
                        .HasColumnType("decimal(8,5)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ReasoningTokens")
                        .HasColumnType("int");

                    b.Property<string>("Residency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("SupportsDocument")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsImage")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsReasoning")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsStructuredOutput")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsText")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Identifier");

                    b.ToTable("LlmDefinitions");
                });

            modelBuilder.Entity("AiHelpers.Data.Entities.PersonalityPrompt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswersJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasDefaultValue("My personality");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[IsDefault] = 1");

                    b.HasIndex("Email", "Name")
                        .IsUnique();

                    b.ToTable("PersonalityPrompts");
                });

            modelBuilder.Entity("AiHelpers.Data.Entities.ProviderCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EncryptedPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Provider")
                        .IsUnique()
                        .HasFilter("[IsDefault] = 1");

                    b.ToTable("ProviderCredentials");
                });

            modelBuilder.Entity("AiHelpers.Data.Entities.SpendCap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MonthlyCapAmount")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SpendCaps");
                });

            modelBuilder.Entity("AiHelpers.Data.Entities.Stylesheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Css")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("StyleInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stylesheets");
                });

            modelBuilder.Entity("AiHelpers.Data.Entities.UserRoleInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("UserRoleInfos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("AiHelpers.Data.Entities.AccountingEntry", b =>
                {
                    b.HasOne("AiHelpers.Data.Entities.HelperDefinition", "HelperDefinition")
                        .WithMany("AccountingEntries")
                        .HasForeignKey("HelperDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HelperDefinition");
                });

            modelBuilder.Entity("AiHelpers.Data.Entities.CallbackEntry", b =>
                {
                    b.HasOne("AiHelpers.Data.Entities.HelperDefinition", "HelperDefinition")
                        .WithMany("CallbackEntries")
                        .HasForeignKey("HelperDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HelperDefinition");
                });

            modelBuilder.Entity("AiHelpers.Data.Entities.Feedback", b =>
                {
                    b.HasOne("AiHelpers.Data.Entities.HelperDefinition", "HelperDefinition")
                        .WithMany("FeedbackEntries")
                        .HasForeignKey("HelperDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HelperDefinition");
                });

            modelBuilder.Entity("AiHelpers.Data.Entities.GeneratedDocument", b =>
                {
                    b.HasOne("AiHelpers.Data.Entities.HelperDefinition", "HelperDefinition")
                        .WithMany()
                        .HasForeignKey("HelperDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HelperDefinition");
                });

            modelBuilder.Entity("AiHelpers.Data.Entities.HelperContextQuestion", b =>
                {
                    b.HasOne("AiHelpers.Data.Entities.HelperDefinition", "HelperDefinition")
                        .WithMany("ContextQuestions")
                        .HasForeignKey("HelperDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HelperDefinition");
                });

            modelBuilder.Entity("AiHelpers.Data.Entities.HelperDefinition", b =>
                {
                    b.HasOne("AiHelpers.Data.Entities.Stylesheet", "DefaultStylesheet")
                        .WithMany("Helpers")
                        .HasForeignKey("DefaultStylesheetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AiHelpers.Data.Entities.HelperCategory", "HelperCategory")
                        .WithMany("Helpers")
                        .HasForeignKey("HelperCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AiHelpers.Data.Entities.LlmDefinition", "LlmDefinition")
                        .WithMany("Helpers")
                        .HasForeignKey("LlmDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefaultStylesheet");

                    b.Navigation("HelperCategory");

                    b.Navigation("LlmDefinition");
                });

            modelBuilder.Entity("AiHelpers.Data.Entities.HelperFavorite", b =>
                {
                    b.HasOne("AiHelpers.Data.Entities.HelperDefinition", "HelperDefinition")
                        .WithMany()
                        .HasForeignKey("HelperDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HelperDefinition");
                });

            modelBuilder.Entity("AiHelpers.Data.Entities.HelperCategory", b =>
                {
                    b.Navigation("Helpers");
                });

            modelBuilder.Entity("AiHelpers.Data.Entities.HelperDefinition", b =>
                {
                    b.Navigation("AccountingEntries");

                    b.Navigation("CallbackEntries");

                    b.Navigation("ContextQuestions");

                    b.Navigation("FeedbackEntries");
                });

            modelBuilder.Entity("AiHelpers.Data.Entities.LlmDefinition", b =>
                {
                    b.Navigation("Helpers");
                });

            modelBuilder.Entity("AiHelpers.Data.Entities.Stylesheet", b =>
                {
                    b.Navigation("Helpers");
                });
#pragma warning restore 612, 618
        }
    }
}
