using System.Net.Http.Json;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;
using AiHelpers.Data.Entities;
using AiHelpers.Data.Enums;
using AiHelpers.Services;

namespace AiHelpers.Providers.Bedrock;

/// <summary>
/// Calls AWS Bedrock's Converse API directly (no WSO2 proxy - see
/// project_ai_helpers_v1_architecture memory for why V1 needed one and V2 doesn't).
/// Only bearer-token auth (AWS's Bedrock API key feature) is implemented, since that's the
/// credential style actually in use. Access key/secret would need SigV4 request signing - not
/// worth building and testing without real IAM credentials to verify it against.
/// </summary>
public class BedrockAdapter(HttpClient httpClient, ICredentialStore credentialStore) : ILlmProviderAdapter
{
    // Without this, models default to a chat-assistant persona - intro remarks, markdown code
    // fences around the actual content, a follow-up question - none of which belongs in a
    // document. Also carries V1's real, proven-in-production instruction for actually getting
    // structured HTML back (headings/tables/lists), not just prose - checked directly against
    // V1's Bedrock request template (Granicus HTTP Integrations.json), which explicitly spells
    // this out; V2 initially assumed this was implied by "inserted into a document as-is" and
    // that assumption was wrong (confirmed side-by-side: identical input to the same Helper
    // produced plain dashed prose in V2 vs proper tables/headings in V1).
    // TODO: move to a provider-agnostic location once a second ILlmProviderAdapter exists - this
    // instruction isn't Bedrock-specific.
    private const string BaselineInstruction =
        "Respond with only the requested content. Do not add introductory or closing remarks, " +
        "do not ask follow-up questions, and do not wrap your response in markdown code fences " +
        "- your entire response is inserted directly into a document as-is. Always respond with " +
        "nicely formatted HTML, including headings, subheadings, paragraphs, line breaks, lists, " +
        "tables and bulleted lists where appropriate. If the input content contains an HTML " +
        "table, respond with a similar table structure. Always use British English rather than " +
        "American English.";

    // Repeated at the END of the system prompts, not just the start - models weight later
    // instructions more heavily, and this directly fixes a real conflict caught in testing: a
    // Helper whose KnowledgePrompt says to "adhere rigidly" to a Word template's plain
    // numbered-paragraph style was producing entirely untagged text, because that Helper-specific
    // instruction (last in the prompt) was winning out over the generic HTML-structure
    // instruction above (first in the prompt). Matching a template's content/section
    // numbering/style and using real HTML tags aren't actually in conflict - this makes that
    // explicit rather than leaving the model to resolve the tension on its own.
    private const string HtmlStructureReinforcement =
        "Regardless of any instructions above about avoiding certain elements (e.g. tables) or " +
        "matching a specific reference document's structure or style, your response must always " +
        "be composed of real, semantic HTML tags - headings as <h2>/<h3>, body text as <p>, " +
        "numbered or bulleted content as <ol>/<ul>/<li>. Matching a template's content, section " +
        "order and numbering is about what the tags contain, not whether you use tags at all - " +
        "never respond with plain, untagged text.";

    // Reinstated as a prompt instruction (V1's original approach - see the Granicus request
    // template) after a brief detour: an earlier version guaranteed this by appending a fixed
    // HTML fragment at render time instead (HelperDetail.razor's BuildOutputDocument), reasoning
    // that "mandatory" shouldn't depend on prompt compliance. That backfired in practice - Will
    // preferred the model's own version (more contextual, e.g. matching the document's language/
    // tone) and the appended version sometimes failed to render as a real table anyway, since
    // string-concatenating trusted HTML after the model's own (sometimes imperfectly-closed) HTML
    // isn't actually a reliable guarantee - a stray unclosed tag in the model's content can drag
    // the appended table into whatever broken nesting resulted. Back to prompting for it, same as
    // V1 did successfully in production.
    private const string ReviewFooterInstruction =
        "At the very end of your response, add a footer notice stating that this content was " +
        "generated by a Conwy AI Helper and may contain errors or omissions if it has not been " +
        "human reviewed. Beneath it, include a real HTML <table> with four review levels: " +
        "1) Not reviewed, 2) Quick check (light skim, minor corrections only), 3) Partial review " +
        "(key sections reviewed, moderate edits), 4) Full review (thoroughly checked and " +
        "approved as accurate) - with a column for initials/signature and a column for date " +
        "against each row. This footer is mandatory and must always be included.";

    // Added only when a Helper has Context Questions configured - positioned LAST in the system
    // prompt array for the same reason HtmlStructureReinforcement is (see above): models weight
    // later instructions more heavily. A context answer can now gate whether entire sections or
    // features appear at all, not just a styling detail, so it needs to be read and planned
    // around BEFORE the model commits to a response structure - not discovered partway through,
    // forcing it to backtrack from (or, more likely, just ignore) content it's already drafted.
    private const string ContextAnswersReinforcement =
        "The user's message may include answers to context questions, provided ahead of the main " +
        "content and labelled with their question. Read and account for ALL of these before you " +
        "begin drafting your response - some may enable, disable, or otherwise change which " +
        "sections, features or level of detail your output should include. Plan your response " +
        "structure around these choices from the outset, rather than discovering a relevant " +
        "answer partway through and needing to backtrack from or ignore content you've already " +
        "committed to.";

    public LlmProvider Provider => LlmProvider.AwsBedrock;

    public async Task<LlmInvocationResult> InvokeAsync(LlmInvocationRequest request, CancellationToken cancellationToken = default)
    {
        var credential = await credentialStore.GetDefaultAsync<AwsCredentialPayload>(LlmProvider.AwsBedrock, cancellationToken)
            ?? throw new InvalidOperationException("No AWS Bedrock credential is configured. Set one at /admin/credentials.");

        if (credential.BearerToken is null)
        {
            throw new NotSupportedException("Only bearer-token AWS credentials are supported right now - access key/secret needs SigV4 signing, not yet implemented.");
        }

        var body = BuildRequestBody(request.Helper, request.Model, request.UserInput, request.Attachments);

        var url = $"https://bedrock-runtime.{credential.Region}.amazonaws.com/model/{Uri.EscapeDataString(request.Model.Identifier)}/converse";
        using var httpRequest = new HttpRequestMessage(HttpMethod.Post, url)
        {
            Content = JsonContent.Create(body)
        };
        httpRequest.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", credential.BearerToken);

        using var response = await httpClient.SendAsync(httpRequest, cancellationToken);
        var responseJson = await response.Content.ReadFromJsonAsync<JsonNode>(cancellationToken: cancellationToken);

        if (!response.IsSuccessStatusCode)
        {
            // AWS error bodies aren't consistent about casing here - seen both "message" and
            // "Message" depending on which layer generates the error.
            var message = responseJson?["message"]?.GetValue<string>()
                ?? responseJson?["Message"]?.GetValue<string>()
                ?? response.ReasonPhrase ?? "Unknown error";
            throw new InvalidOperationException($"Bedrock call failed ({(int)response.StatusCode}): {message}");
        }

        var contentBlocks = responseJson?["output"]?["message"]?["content"]?.AsArray() ?? [];
        var text = string.Concat(contentBlocks
            .Select(block => block?["text"]?.GetValue<string>())
            .Where(t => t is not null));

        return new LlmInvocationResult
        {
            Text = text,
            InputTokens = responseJson?["usage"]?["inputTokens"]?.GetValue<int>() ?? 0,
            OutputTokens = responseJson?["usage"]?["outputTokens"]?.GetValue<int>() ?? 0,
            StopReason = responseJson?["stopReason"]?.GetValue<string>()
        };
    }

    private static JsonObject BuildRequestBody(HelperDefinition helper, LlmDefinition model, string userInput, IReadOnlyList<Attachment> attachments)
    {
        var systemPrompts = new[]
        {
            BaselineInstruction,
            helper.PrimaryPurpose,
            helper.Methodology,
            helper.StyleTone,
            helper.OutputFormat,
            helper.TargetAudience,
            helper.SpecialInstructions,
            // Matches V1's "This is how you should use the knowledge document (if provided)"
            // system prompt entry - the document itself is attached as a content block (see
            // HelperInvocationService.BuildAttachments), this just tells the model how to treat it.
            helper.HasKnowledge && !string.IsNullOrWhiteSpace(helper.KnowledgePrompt)
                ? $"This is how you should use the attached reference document: {helper.KnowledgePrompt}"
                : null,
            HtmlStructureReinforcement,
            ReviewFooterInstruction,
            helper.ContextQuestions.Count > 0 ? ContextAnswersReinforcement : null
        }.Where(p => !string.IsNullOrWhiteSpace(p));

        // Documents/images before the text block - the order the Converse API examples use, and
        // it reads naturally as "here's the material, now here's what to do with it".
        var content = new JsonArray();
        foreach (var attachment in attachments)
        {
            content.Add(attachment.Kind == AttachmentKind.Document
                ? new JsonObject
                {
                    ["document"] = new JsonObject
                    {
                        ["name"] = SanitizeDocumentName(attachment.Name),
                        ["format"] = attachment.Format,
                        ["source"] = new JsonObject { ["bytes"] = Convert.ToBase64String(attachment.Bytes) }
                    }
                }
                : new JsonObject
                {
                    ["image"] = new JsonObject
                    {
                        ["format"] = attachment.Format,
                        ["source"] = new JsonObject { ["bytes"] = Convert.ToBase64String(attachment.Bytes) }
                    }
                });
        }
        // Converse rejects an empty text content block outright - a real failure mode once
        // attachments made "no typed input, just a file" a normal thing to submit (V1 forced an
        // either/or choice between text and a file, so this never came up there).
        var effectiveInput = string.IsNullOrWhiteSpace(userInput) && attachments.Count > 0
            ? "Process the attached file(s)."
            : userInput;
        content.Add(new JsonObject { ["text"] = effectiveInput });

        var body = new JsonObject
        {
            ["system"] = new JsonArray(systemPrompts.Select(p => (JsonNode)new JsonObject { ["text"] = p }).ToArray()),
            ["messages"] = new JsonArray(
                new JsonObject
                {
                    ["role"] = "user",
                    ["content"] = content
                })
        };

        // When Effort engages reasoning, request thinking config.
        if (helper.Effort is { } effort && model.SupportsReasoning)
        {
            var maxBudget = model.ReasoningTokens ?? 4096;
            var budgetTokens = effort switch
            {
                EffortLevel.Low => (int)(maxBudget * 0.25),
                EffortLevel.Medium => (int)(maxBudget * 0.5),
                EffortLevel.High => maxBudget,
                _ => maxBudget
            };

            body["additionalModelRequestFields"] = new JsonObject
            {
                ["thinking"] = new JsonObject
                {
                    ["type"] = "enabled",
                    ["budget_tokens"] = budgetTokens
                }
            };
        }

        // Deliberately never send temperature/top_p (Creativity/Adherence) - Will already went
        // through this exact fight in V1 and concluded it wasn't worth it: different Bedrock
        // models reject sampling params in different, inconsistent ways (some reject them
        // entirely, some reject temperature+top_p together but accept one, presumably more
        // variations exist). Rather than chase each one as it surfaces, models just use their
        // own defaults. Creativity/Adherence stay in the schema (real V1 data, may matter for a
        // future non-Bedrock provider) but Bedrock calls never reference them.

        return body;
    }

    /// <summary>
    /// Documents/images before the text block - the order the Converse API examples use, and it
    /// reads naturally as "here's the material, now here's what to do with it". Shared between
    /// history turns and the current turn so both build content blocks identically.
    /// </summary>
    private static JsonArray BuildContentBlocks(string text, IReadOnlyList<Attachment> attachments)
    {
        var content = new JsonArray();
        foreach (var attachment in attachments)
        {
            content.Add(attachment.Kind == AttachmentKind.Document
                ? new JsonObject
                {
                    ["document"] = new JsonObject
                    {
                        ["name"] = SanitizeDocumentName(attachment.Name),
                        ["format"] = attachment.Format,
                        ["source"] = new JsonObject { ["bytes"] = Convert.ToBase64String(attachment.Bytes) }
                    }
                }
                : new JsonObject
                {
                    ["image"] = new JsonObject
                    {
                        ["format"] = attachment.Format,
                        ["source"] = new JsonObject { ["bytes"] = Convert.ToBase64String(attachment.Bytes) }
                    }
                });
        }
        content.Add(new JsonObject { ["text"] = text });
        return content;
    }

    /// <summary>
    /// DocumentBlock.name only allows alphanumerics, single whitespace, hyphens, parentheses and
    /// square brackets - a real filename's extension/underscores/etc. would otherwise get
    /// rejected outright. The extension is dropped entirely since Format already conveys it.
    /// </summary>
    private static string SanitizeDocumentName(string fileName)
    {
        var name = System.IO.Path.GetFileNameWithoutExtension(fileName);
        var cleaned = Regex.Replace(name, @"[^A-Za-z0-9\s\-()\[\]]", " ");
        cleaned = Regex.Replace(cleaned, @"\s+", " ").Trim();
        if (cleaned.Length == 0) return "Attachment";
        return cleaned.Length > 200 ? cleaned[..200] : cleaned;
    }
}
